GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "sample 1",
    "author": "miffi",
    "url": "localhost:3001",
    "likes": 9999
}